#!/bin/sh

URL='http://pgl.yoyo.org/adservers/serverlist.php?hostformat=unbound&showintro=0&mimetype=plaintext'
FILE='/var/unbound/etc/unbound-adservers.conf'

ftp -Vo $FILE $URL

rcctl reload unbound
