#!/bin/sh

URL='https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell'
FILE='VQHA80.csv'
STATION='GOE'
DEST='loxone'

transfer() {
	local _par=$1 _port=$2 _val

	_val=`awk \
	    -v stn="$STATION" \
	    -v par="$_par" \
	    -F \; \
	    '{if ($1 == stn) {print $par}}' \
	    /tmp/$FILE`

	[ $_val != "-" ] && echo $_val | nc -uw 1 $DEST $_port
}

ftp -MVo /tmp/$FILE $URL/$FILE

transfer 3 6003		# lufttemperatur
transfer 7 6004		# relative luftfeuchtigkeit
transfer 12 6005	# luftdruck
